# Generated by Django 4.2.1 on 2023-05-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='under_30',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
