# Generated by Django 4.2.1 on 2023-05-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_under_30'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='under_30',
        ),
    ]
