# Generated by Django 4.2.1 on 2023-05-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(default='https://placehold.co/300x225', upload_to='images/'),
        ),
    ]
