# Generated by Django 4.2.1 on 2023-05-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_aggregaterating_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AggregateRating',
        ),
    ]
